[2025-01-16T19:22:20.508+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_process_with_excel_report.extract_data manual__2025-01-16T19:22:15.334325+00:00 [queued]>
[2025-01-16T19:22:20.515+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_process_with_excel_report.extract_data manual__2025-01-16T19:22:15.334325+00:00 [queued]>
[2025-01-16T19:22:20.515+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-01-16T19:22:20.530+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract_data> on 2025-01-16 19:22:15.334325+00:00
[2025-01-16T19:22:20.610+0000] {standard_task_runner.py:57} INFO - Started process 212 to run task
[2025-01-16T19:22:20.620+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_process_with_excel_report', 'extract_data', 'manual__2025-01-16T19:22:15.334325+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/db_to_xls.py', '--cfg-path', '/tmp/tmpjzjiqx8n']
[2025-01-16T19:22:20.672+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask extract_data
[2025-01-16T19:22:20.914+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_process_with_excel_report.extract_data manual__2025-01-16T19:22:15.334325+00:00 [running]> on host 8c28df1b72a3
[2025-01-16T19:22:21.281+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_process_with_excel_report' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-16T19:22:15.334325+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-16T19:22:15.334325+00:00'
[2025-01-16T19:22:21.306+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-16T19:22:21.403+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.9/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-01-16T19:22:21.457+0000] {db_to_xls.py:30} ERROR - Error extracting data: Execution failed on sql 'SELECT * FROM sprout.Users;': permission denied for schema sprout
LINE 1: SELECT * FROM sprout.Users;
                      ^

[2025-01-16T19:22:21.460+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/sql.py", line 2202, in execute
    cur.execute(sql, *args)
psycopg2.errors.InsufficientPrivilege: permission denied for schema sprout
LINE 1: SELECT * FROM sprout.Users;
                      ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/db_to_xls.py", line 23, in extract_data
    df = postgres_hook.get_pandas_df(query)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/hooks/sql.py", line 219, in get_pandas_df
    return psql.read_sql(sql, con=conn, params=parameters, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/sql.py", line 635, in read_sql
    return pandas_sql.read_query(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/sql.py", line 2266, in read_query
    cursor = self.execute(sql, params)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/sql.py", line 2214, in execute
    raise ex from exc
pandas.errors.DatabaseError: Execution failed on sql 'SELECT * FROM sprout.Users;': permission denied for schema sprout
LINE 1: SELECT * FROM sprout.Users;
                      ^

[2025-01-16T19:22:21.552+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_process_with_excel_report, task_id=extract_data, execution_date=20250116T192215, start_date=20250116T192220, end_date=20250116T192221
[2025-01-16T19:22:21.571+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 6 for task extract_data (Execution failed on sql 'SELECT * FROM sprout.Users;': permission denied for schema sprout
LINE 1: SELECT * FROM sprout.Users;
                      ^
; 212)
[2025-01-16T19:22:21.669+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-16T19:22:21.740+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
