[2025-01-17T18:46:31.677+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_process_with_excel_report.generate_excel_report manual__2025-01-17T18:14:22.678923+00:00 [queued]>
[2025-01-17T18:46:31.737+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_process_with_excel_report.generate_excel_report manual__2025-01-17T18:14:22.678923+00:00 [queued]>
[2025-01-17T18:46:31.739+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-01-17T18:46:31.762+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): generate_excel_report> on 2025-01-17 18:14:22.678923+00:00
[2025-01-17T18:46:31.847+0000] {standard_task_runner.py:57} INFO - Started process 298 to run task
[2025-01-17T18:46:31.894+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_process_with_excel_report', 'generate_excel_report', 'manual__2025-01-17T18:14:22.678923+00:00', '--job-id', '96', '--raw', '--subdir', 'DAGS_FOLDER/db_to_xls.py', '--cfg-path', '/tmp/tmpt3_1nrxw']
[2025-01-17T18:46:31.908+0000] {standard_task_runner.py:85} INFO - Job 96: Subtask generate_excel_report
[2025-01-17T18:46:31.972+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_process_with_excel_report.generate_excel_report manual__2025-01-17T18:14:22.678923+00:00 [running]> on host 6b8a819d6b33
[2025-01-17T18:46:32.221+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_process_with_excel_report' AIRFLOW_CTX_TASK_ID='generate_excel_report' AIRFLOW_CTX_EXECUTION_DATE='2025-01-17T18:14:22.678923+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-17T18:14:22.678923+00:00'
[2025-01-17T18:46:32.226+0000] {db_to_xls.py:304} INFO - Fetching data for user_profiling
[2025-01-17T18:46:32.309+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-17T18:46:32.462+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.9/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-01-17T18:46:32.533+0000] {db_to_xls.py:306} INFO - Fetched 14 rows for user_profiling
[2025-01-17T18:46:32.534+0000] {db_to_xls.py:304} INFO - Fetching data for transaction_type
[2025-01-17T18:46:32.586+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-17T18:46:32.654+0000] {db_to_xls.py:306} INFO - Fetched 10 rows for transaction_type
[2025-01-17T18:46:32.655+0000] {db_to_xls.py:304} INFO - Fetching data for daily_activity_report
[2025-01-17T18:46:32.675+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-17T18:46:32.696+0000] {db_to_xls.py:306} INFO - Fetched 6 rows for daily_activity_report
[2025-01-17T18:46:32.696+0000] {db_to_xls.py:304} INFO - Fetching data for transactions_with_mdr
[2025-01-17T18:46:32.753+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-17T18:46:32.830+0000] {db_to_xls.py:306} INFO - Fetched 14 rows for transactions_with_mdr
[2025-01-17T18:46:33.066+0000] {db_to_xls.py:313} INFO - Written sheet user_profiling with 14 rows.
[2025-01-17T18:46:33.110+0000] {db_to_xls.py:313} INFO - Written sheet transaction_type with 10 rows.
[2025-01-17T18:46:33.112+0000] {db_to_xls.py:313} INFO - Written sheet daily_activity_report with 6 rows.
[2025-01-17T18:46:33.126+0000] {db_to_xls.py:313} INFO - Written sheet transactions_with_mdr with 14 rows.
[2025-01-17T18:46:33.147+0000] {db_to_xls.py:315} INFO - Excel report successfully generated at: ./data/report.xlsx
[2025-01-17T18:46:33.151+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-01-17T18:46:33.217+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_process_with_excel_report, task_id=generate_excel_report, execution_date=20250117T181422, start_date=20250117T184631, end_date=20250117T184633
[2025-01-17T18:46:33.398+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-01-17T18:46:33.514+0000] {taskinstance.py:2784} INFO - 1 downstream tasks scheduled from follow-on schedule check
