[2025-01-17T17:41:52.437+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_process_with_excel_report.load_data manual__2025-01-17T17:24:34.119787+00:00 [queued]>
[2025-01-17T17:41:52.506+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_process_with_excel_report.load_data manual__2025-01-17T17:24:34.119787+00:00 [queued]>
[2025-01-17T17:41:52.509+0000] {taskinstance.py:1361} INFO - Starting attempt 5 of 5
[2025-01-17T17:41:52.572+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_data> on 2025-01-17 17:24:34.119787+00:00
[2025-01-17T17:41:52.644+0000] {standard_task_runner.py:57} INFO - Started process 477 to run task
[2025-01-17T17:41:52.654+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_process_with_excel_report', 'load_data', 'manual__2025-01-17T17:24:34.119787+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/db_to_xls.py', '--cfg-path', '/tmp/tmpuhofjbs9']
[2025-01-17T17:41:52.699+0000] {standard_task_runner.py:85} INFO - Job 71: Subtask load_data
[2025-01-17T17:41:52.978+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_process_with_excel_report.load_data manual__2025-01-17T17:24:34.119787+00:00 [running]> on host e075edadbc7d
[2025-01-17T17:41:53.422+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_process_with_excel_report' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-17T17:24:34.119787+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-17T17:24:34.119787+00:00'
[2025-01-17T17:41:53.682+0000] {db_to_xls.py:262} ERROR - Error during data loading: Missing column provided to 'parse_dates': 'expiry_date, purchase_date'
[2025-01-17T17:41:53.684+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/db_to_xls.py", line 165, in load_data
    user_profiling = load_and_clean_csv(user_profiling_path)
  File "/opt/airflow/dags/db_to_xls.py", line 152, in load_and_clean_csv
    df = pd.read_csv(file_path, dtype=custom_dtypes, parse_dates=["timestamp", "purchase_date", "expiry_date"])
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1679, in _make_engine
    return mapping[engine](f, **self.options)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 161, in __init__
    self._validate_parse_dates_presence(self.names)  # type: ignore[has-type]
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parsers/base_parser.py", line 230, in _validate_parse_dates_presence
    raise ValueError(
ValueError: Missing column provided to 'parse_dates': 'expiry_date, purchase_date'
[2025-01-17T17:41:53.712+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_process_with_excel_report, task_id=load_data, execution_date=20250117T172434, start_date=20250117T174152, end_date=20250117T174153
[2025-01-17T17:41:53.773+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 71 for task load_data (Missing column provided to 'parse_dates': 'expiry_date, purchase_date'; 477)
[2025-01-17T17:41:53.873+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-17T17:41:54.011+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
