[2025-01-17T19:07:06.221+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_process_with_excel_report.export_report manual__2025-01-17T18:14:22.678923+00:00 [queued]>
[2025-01-17T19:07:06.241+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_process_with_excel_report.export_report manual__2025-01-17T18:14:22.678923+00:00 [queued]>
[2025-01-17T19:07:06.243+0000] {taskinstance.py:1361} INFO - Starting attempt 21 of 21
[2025-01-17T19:07:06.308+0000] {taskinstance.py:1382} INFO - Executing <Task(SSHOperator): export_report> on 2025-01-17 18:14:22.678923+00:00
[2025-01-17T19:07:06.385+0000] {standard_task_runner.py:57} INFO - Started process 618 to run task
[2025-01-17T19:07:06.426+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_process_with_excel_report', 'export_report', 'manual__2025-01-17T18:14:22.678923+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/db_to_xls.py', '--cfg-path', '/tmp/tmpyj17_7hq']
[2025-01-17T19:07:06.440+0000] {standard_task_runner.py:85} INFO - Job 107: Subtask export_report
[2025-01-17T19:07:06.671+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_process_with_excel_report.export_report manual__2025-01-17T18:14:22.678923+00:00 [running]> on host 6b8a819d6b33
[2025-01-17T19:07:06.825+0000] {abstractoperator.py:696} ERROR - Exception rendering Jinja template for task 'export_report', field 'command'. Template: 'bash ./scripts/export_report.sh'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 688, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/template/templater.py", line 153, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.9/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash ./scripts/export_report.sh
[2025-01-17T19:07:06.829+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1646, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2291, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1244, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 688, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/template/templater.py", line 153, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.9/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash ./scripts/export_report.sh
[2025-01-17T19:07:06.905+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_process_with_excel_report, task_id=export_report, execution_date=20250117T181422, start_date=20250117T190706, end_date=20250117T190706
[2025-01-17T19:07:06.987+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 107 for task export_report (bash ./scripts/export_report.sh; 618)
[2025-01-17T19:07:07.121+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-17T19:07:07.178+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
