[2025-01-17T18:20:20.700+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_process_with_excel_report.export_report manual__2025-01-17T18:14:22.678923+00:00 [queued]>
[2025-01-17T18:20:20.717+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_process_with_excel_report.export_report manual__2025-01-17T18:14:22.678923+00:00 [queued]>
[2025-01-17T18:20:20.718+0000] {taskinstance.py:1361} INFO - Starting attempt 5 of 5
[2025-01-17T18:20:20.728+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): export_report> on 2025-01-17 18:14:22.678923+00:00
[2025-01-17T18:20:20.741+0000] {standard_task_runner.py:57} INFO - Started process 550 to run task
[2025-01-17T18:20:20.746+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_process_with_excel_report', 'export_report', 'manual__2025-01-17T18:14:22.678923+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/db_to_xls.py', '--cfg-path', '/tmp/tmp_kokwvj7']
[2025-01-17T18:20:20.751+0000] {standard_task_runner.py:85} INFO - Job 89: Subtask export_report
[2025-01-17T18:20:20.872+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_process_with_excel_report.export_report manual__2025-01-17T18:14:22.678923+00:00 [running]> on host b83a74940c8c
[2025-01-17T18:20:21.005+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_process_with_excel_report' AIRFLOW_CTX_TASK_ID='export_report' AIRFLOW_CTX_EXECUTION_DATE='2025-01-17T18:14:22.678923+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-17T18:14:22.678923+00:00'
[2025-01-17T18:20:21.012+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-01-17T18:20:21.015+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker cp sprout_etl_project-scheduler-1:/opt/***/data/report.xlsx /Users/abror/Documents/personal/test_assignment/sprout/sprout_etl_project/data/report.xlsx']
[2025-01-17T18:20:21.080+0000] {subprocess.py:86} INFO - Output:
[2025-01-17T18:20:21.267+0000] {subprocess.py:93} INFO - invalid output path: directory "/Users/abror/Documents/personal/test_assignment/sprout/sprout_etl_project/data" does not exist
[2025-01-17T18:20:21.273+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-01-17T18:20:21.340+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-01-17T18:20:21.347+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_process_with_excel_report, task_id=export_report, execution_date=20250117T181422, start_date=20250117T182020, end_date=20250117T182021
[2025-01-17T18:20:21.402+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 89 for task export_report (Bash command failed. The command returned a non-zero exit code 1.; 550)
[2025-01-17T18:20:21.474+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-17T18:20:21.553+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
