[2025-01-17T18:25:54.283+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_process_with_excel_report.export_report manual__2025-01-17T18:14:22.678923+00:00 [queued]>
[2025-01-17T18:25:54.300+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_process_with_excel_report.export_report manual__2025-01-17T18:14:22.678923+00:00 [queued]>
[2025-01-17T18:25:54.301+0000] {taskinstance.py:1361} INFO - Starting attempt 7 of 7
[2025-01-17T18:25:54.314+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): export_report> on 2025-01-17 18:14:22.678923+00:00
[2025-01-17T18:25:54.336+0000] {standard_task_runner.py:57} INFO - Started process 641 to run task
[2025-01-17T18:25:54.342+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_process_with_excel_report', 'export_report', 'manual__2025-01-17T18:14:22.678923+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/db_to_xls.py', '--cfg-path', '/tmp/tmphkwo1cha']
[2025-01-17T18:25:54.347+0000] {standard_task_runner.py:85} INFO - Job 91: Subtask export_report
[2025-01-17T18:25:54.634+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_process_with_excel_report.export_report manual__2025-01-17T18:14:22.678923+00:00 [running]> on host b83a74940c8c
[2025-01-17T18:25:55.447+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_process_with_excel_report' AIRFLOW_CTX_TASK_ID='export_report' AIRFLOW_CTX_EXECUTION_DATE='2025-01-17T18:14:22.678923+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-17T18:14:22.678923+00:00'
[2025-01-17T18:25:55.473+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-01-17T18:25:55.477+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker cp sprout_etl_project-scheduler-1:/opt/***/data/report.xlsx Users/abror/Documents/personal/test_assignment/sprout/sprout_etl_project/data/report.xlsx']
[2025-01-17T18:25:55.523+0000] {subprocess.py:86} INFO - Output:
[2025-01-17T18:25:55.721+0000] {subprocess.py:93} INFO - invalid output path: directory "/tmp/***tmpmu0pje2d/Users/abror/Documents/personal/test_assignment/sprout/sprout_etl_project/data" does not exist
[2025-01-17T18:25:55.727+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-01-17T18:25:55.846+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-01-17T18:25:55.960+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_process_with_excel_report, task_id=export_report, execution_date=20250117T181422, start_date=20250117T182554, end_date=20250117T182555
[2025-01-17T18:25:56.066+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 91 for task export_report (Bash command failed. The command returned a non-zero exit code 1.; 641)
[2025-01-17T18:25:56.270+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-17T18:25:56.447+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
