[2025-01-17T18:14:50.442+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_process_with_excel_report.export_report manual__2025-01-17T18:14:22.678923+00:00 [queued]>
[2025-01-17T18:14:50.461+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_process_with_excel_report.export_report manual__2025-01-17T18:14:22.678923+00:00 [queued]>
[2025-01-17T18:14:50.463+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-01-17T18:14:50.518+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): export_report> on 2025-01-17 18:14:22.678923+00:00
[2025-01-17T18:14:50.585+0000] {standard_task_runner.py:57} INFO - Started process 423 to run task
[2025-01-17T18:14:50.605+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_process_with_excel_report', 'export_report', 'manual__2025-01-17T18:14:22.678923+00:00', '--job-id', '85', '--raw', '--subdir', 'DAGS_FOLDER/db_to_xls.py', '--cfg-path', '/tmp/tmp_hq_1i_e']
[2025-01-17T18:14:50.614+0000] {standard_task_runner.py:85} INFO - Job 85: Subtask export_report
[2025-01-17T18:14:50.852+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_process_with_excel_report.export_report manual__2025-01-17T18:14:22.678923+00:00 [running]> on host b83a74940c8c
[2025-01-17T18:14:51.132+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_process_with_excel_report' AIRFLOW_CTX_TASK_ID='export_report' AIRFLOW_CTX_EXECUTION_DATE='2025-01-17T18:14:22.678923+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-17T18:14:22.678923+00:00'
[2025-01-17T18:14:51.145+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-01-17T18:14:51.148+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker cp ***_webserver:/opt/***/data/report.xlsx ~//Users/abror/Documents/personal/test_assignment/sprout/sprout_etl_project/data/report.xlsx']
[2025-01-17T18:14:51.204+0000] {subprocess.py:86} INFO - Output:
[2025-01-17T18:14:51.655+0000] {subprocess.py:93} INFO - invalid output path: directory "/home/***/Users/abror/Documents/personal/test_assignment/sprout/sprout_etl_project/data" does not exist
[2025-01-17T18:14:51.661+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-01-17T18:14:51.730+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-01-17T18:14:51.739+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_process_with_excel_report, task_id=export_report, execution_date=20250117T181422, start_date=20250117T181450, end_date=20250117T181451
[2025-01-17T18:14:51.804+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 85 for task export_report (Bash command failed. The command returned a non-zero exit code 1.; 423)
[2025-01-17T18:14:51.944+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-17T18:14:52.047+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
