[2025-01-17T14:56:28.420+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_process_with_excel_report.extract_data scheduled__2025-01-16T00:00:00+00:00 [queued]>
[2025-01-17T14:56:28.430+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_process_with_excel_report.extract_data scheduled__2025-01-16T00:00:00+00:00 [queued]>
[2025-01-17T14:56:28.431+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-01-17T14:56:28.441+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract_data> on 2025-01-16 00:00:00+00:00
[2025-01-17T14:56:28.450+0000] {standard_task_runner.py:57} INFO - Started process 179 to run task
[2025-01-17T14:56:28.456+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_process_with_excel_report', 'extract_data', 'scheduled__2025-01-16T00:00:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/db_to_xls.py', '--cfg-path', '/tmp/tmpv8j5ax0b']
[2025-01-17T14:56:28.462+0000] {standard_task_runner.py:85} INFO - Job 27: Subtask extract_data
[2025-01-17T14:56:28.547+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_process_with_excel_report.extract_data scheduled__2025-01-16T00:00:00+00:00 [running]> on host 4e4dfd1b49e6
[2025-01-17T14:56:28.648+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_process_with_excel_report' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-16T00:00:00+00:00'
[2025-01-17T14:56:28.679+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-17T14:56:28.732+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.9/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-01-17T14:56:28.759+0000] {db_to_xls.py:28} INFO - Extracted Users and saved to /tmp/Users.csv.
[2025-01-17T14:56:28.774+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-17T14:56:28.796+0000] {db_to_xls.py:28} INFO - Extracted Transactions and saved to /tmp/Transactions.csv.
[2025-01-17T14:56:28.809+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-17T14:56:28.825+0000] {db_to_xls.py:28} INFO - Extracted Membership_Purchases and saved to /tmp/Membership_Purchases.csv.
[2025-01-17T14:56:28.839+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-17T14:56:28.855+0000] {db_to_xls.py:28} INFO - Extracted MDR_Data and saved to /tmp/MDR_Data.csv.
[2025-01-17T14:56:28.868+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-17T14:56:28.883+0000] {db_to_xls.py:28} INFO - Extracted User_Activity and saved to /tmp/User_Activity.csv.
[2025-01-17T14:56:28.905+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-01-17T14:56:28.920+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_process_with_excel_report, task_id=extract_data, execution_date=20250116T000000, start_date=20250117T145628, end_date=20250117T145628
[2025-01-17T14:56:28.955+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-01-17T14:56:28.987+0000] {taskinstance.py:2784} INFO - 1 downstream tasks scheduled from follow-on schedule check
