[2025-01-17T19:39:37.248+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_process_with_excel_report.extract_data manual__2025-01-17T19:39:27.884537+00:00 [queued]>
[2025-01-17T19:39:37.262+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_process_with_excel_report.extract_data manual__2025-01-17T19:39:27.884537+00:00 [queued]>
[2025-01-17T19:39:37.263+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-01-17T19:39:37.330+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract_data> on 2025-01-17 19:39:27.884537+00:00
[2025-01-17T19:39:37.466+0000] {standard_task_runner.py:57} INFO - Started process 187 to run task
[2025-01-17T19:39:37.521+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_process_with_excel_report', 'extract_data', 'manual__2025-01-17T19:39:27.884537+00:00', '--job-id', '116', '--raw', '--subdir', 'DAGS_FOLDER/db_to_xls.py', '--cfg-path', '/tmp/tmpmbrf_zia']
[2025-01-17T19:39:37.538+0000] {standard_task_runner.py:85} INFO - Job 116: Subtask extract_data
[2025-01-17T19:39:37.915+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_process_with_excel_report.extract_data manual__2025-01-17T19:39:27.884537+00:00 [running]> on host 74a34ea28e1a
[2025-01-17T19:39:38.014+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_process_with_excel_report' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-17T19:39:27.884537+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-17T19:39:27.884537+00:00'
[2025-01-17T19:39:38.100+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-17T19:39:38.310+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.9/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-01-17T19:39:38.431+0000] {db_to_xls.py:30} INFO - Extracted Users and saved to /tmp/Users.csv.
[2025-01-17T19:39:38.455+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-17T19:39:38.610+0000] {db_to_xls.py:30} INFO - Extracted Transactions and saved to /tmp/Transactions.csv.
[2025-01-17T19:39:38.670+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-17T19:39:38.705+0000] {db_to_xls.py:30} INFO - Extracted Membership_Purchases and saved to /tmp/Membership_Purchases.csv.
[2025-01-17T19:39:38.770+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-17T19:39:38.828+0000] {db_to_xls.py:30} INFO - Extracted MDR_Data and saved to /tmp/MDR_Data.csv.
[2025-01-17T19:39:38.855+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-17T19:39:38.933+0000] {db_to_xls.py:30} INFO - Extracted User_Activity and saved to /tmp/User_Activity.csv.
[2025-01-17T19:39:39.017+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-01-17T19:39:39.038+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_process_with_excel_report, task_id=extract_data, execution_date=20250117T193927, start_date=20250117T193937, end_date=20250117T193939
[2025-01-17T19:39:39.217+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-01-17T19:39:39.331+0000] {taskinstance.py:2784} INFO - 1 downstream tasks scheduled from follow-on schedule check
